apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-observability-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana-observability
    environment: dev
spec:
  project: default
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: grafana
      targetRevision: '8.5.1'
      helm:
        valueFiles:
          - '$values/helm/observability/grafana-values.yaml'
    - repoURL: 'https://github.com/nubenetes/jenkins-without-git-parameter.git'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
